const cartTypes = {
	TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
	ADD_ITEM: "ADD_ITEM",
	REMOVE_ITEM: "REMOVE_ITEM",
	REDUCE_QUANTITY: "REDUCE_QUANTITY",
	CLEAR_CART: "CLEAR_CART",
};

export default cartTypes;
