const UserTypes = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
	GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
	GOOGLE_SIGN_IN_FAILED: "GOOGLE_SIGN_IN_FAILED",
	EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
	EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
	EMAIL_SIGN_IN_FAILED: "EMAIL_SIGN_IN_FAILED",
};

export default UserTypes;
